name: build
on: 
  push:
    branches:
      - 'current'
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build WAR
      run: mvn --no-transfer-progress -B install
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: S{{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push image
      run: |
        docker build -f Dockerfile -t ${{ secrets.DOCKER_REGISTRY }}/piranhacloud/start:latest .
        docker push ${{ secrets.DOCKER_REGISTRY }}/piranhacloud/start:latest
