name: build
on: 
  push:
    branches:
      - 'current'
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build WAR
      run: |
        sudo apt-get install libegl1\                                                                  ║
            libvpx7\                                                                                   ║
            libevent-2.1-7\                                                                            ║
            libopus0\                                                                                  ║
            libopengl0\                                                                                ║
            libwoff1\                                                                                  ║
            libharfbuzz-icu0\                                                                          ║
            libgstreamer-plugins-base1.0-0\                                                            ║
            libgstreamer-gl1.0-0\                                                                      ║
            libhyphen0\                                                                                ║
            libmanette-0.2-0\                                                                          ║
            libgles2\                                                                                  ║
            gstreamer1.0-libav                                                                         ║
        mvn --no-transfer-progress -B install
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push image
      run: |
        docker build -f Dockerfile -t ghcr.io/piranhacloud/start:latest .
        docker push ghcr.io/piranhacloud/start:latest
